function [fitresult, gof] = createFit_smoothingspline(foci2,num)
%CREATEFIT1(FOCI2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: foci2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Apr-2020 18:20:16


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], foci2 );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = num;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'foci2', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% ylabel( 'foci2', 'Interpreter', 'none' );
% grid on


